jobs:
- name: hello-world-job
  plan:
  - task: hello-world-task
    config: 
      # tells concourse the type of worker this task should run on
      platform: linux

      # specify containter image to use for task
      image_resource:
        type: registry-image
        source:
          repository: busybox

      outputs:
      - name: the-artifact

      run:
        path: sh
        args: 
        - -cx
        - |
          ls -l .
          echo "hello from another step!" > the-artifact/message

  - task: read-the-artifact
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: busybox
      # To receive "the-artifact", specify it as an input
      inputs:
      - name: the-artifact
      run:
        path: sh
        args:
        - -cx
        - |
          ls -l .
          cat the-artifact/message
        
